name: uk_visa_test
description: UK Visa Test - Life in the UK Practice App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1

  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.3

  # Network & API
  http: ^1.1.2
  dio: ^5.4.0

  # Storage & Cache
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication & Security
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Utils
  uuid: ^4.2.1
  timeago: ^3.6.0
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1

  # UI Components
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  pull_to_refresh: ^2.0.0

  # Charts & Analytics
  fl_chart: ^0.65.0
  percent_indicator: ^4.2.3

  # Audio (for pronunciation if needed)
  just_audio: ^0.9.36

  # In-app purchases
  in_app_purchase: ^3.1.11
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/

  fonts:
    - family: UKVisa
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false